Data can be in multiple formats.
1.CSV FILE
2. TSV FILE
3. JSON FILE
4. Text

Dataset : Kaggle,UCI,Sklearn dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [3]:
from sklearn.datasets import load_boston

In [8]:
housing_data = load_boston() #the variable contains the data

In [9]:
housing_data

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [10]:
type(housing_data)

sklearn.utils.Bunch

In [11]:
print(housing_data.keys()) # to see the keys available wrt the values

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])


In [12]:
#Features- Data
#Output-Target

In [14]:
print(housing_data['DESCR'])
#13 columns and 506 rows

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [15]:
df = pd.DataFrame(housing_data.data)
df

0     1      2    3      4   ...   8      9     10      11    12
0    0.00632  18.0   2.31  0.0  0.538  ...  1.0  296.0  15.3  396.90  4.98
1    0.02731   0.0   7.07  0.0  0.469  ...  2.0  242.0  17.8  396.90  9.14
2    0.02729   0.0   7.07  0.0  0.469  ...  2.0  242.0  17.8  392.83  4.03
3    0.03237   0.0   2.18  0.0  0.458  ...  3.0  222.0  18.7  394.63  2.94
4    0.06905   0.0   2.18  0.0  0.458  ...  3.0  222.0  18.7  396.90  5.33
..       ...   ...    ...  ...    ...  ...  ...    ...   ...     ...   ...
501  0.06263   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  391.99  9.67
502  0.04527   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  9.08
503  0.06076   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  5.64
504  0.10959   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  393.45  6.48
505  0.04741   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  7.88

[506 rows x 13 columns]

In [16]:
#To get column name
df = pd.DataFrame(housing_data.data)
df.columns = housing_data.feature_names
df
#Below mentioned data just contains i/p one row needs to be added for o/p

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [17]:
df['Price'] = housing_data.target
df.head() #only first 5 rows

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

In [23]:
#Method1
x = df.iloc[:,0:13].values#it will go from 0 to 12
y=df.iloc[:,13].values
print(x)
print(y)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

In [ ]:
# 14 columns(0 to 13)
#input is from 0 to 12
#output is the 13th column

In [ ]:
#Method 2
#x = df.drop('Price',axis =1)#axis=1 is column,axis=0 is row
#y = df['Price']

In [ ]:
# Data in the form i/p or o/p
#Splitting of Data = Training+Testing
#4 values:
#input Training
#output Training
#input Training
#output Training


In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state = 50) #dont change the order since first o/p is train second is test then 3rd is the output of y
#i.e, train and test # test value will be 30% and train value will be 70% if random state is 1, then seed value is 1 and it will take alternatevalues
#for train and test and if it is 2 then every 3rd data will be chosen


In [25]:
x_train.shape

(354, 13)

In [27]:
x_test.shape

(152, 13)

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train) #only train data
y_pred = model.predict(x_test)
y_pred #predicted output

array([ 9.70536163e+00,  2.52526846e+01,  1.99563787e+01,  2.78890172e+01,
        2.22739530e+01,  2.32476003e+01,  1.62794573e+01,  1.69545473e+01,
        1.29304677e+01,  2.49423296e+01,  1.44246339e+01,  2.86653627e+01,
        1.76944262e+01,  3.46031656e+01,  1.85769591e+01,  1.35355785e+01,
        1.40027050e+01,  2.86569561e+01,  2.24340994e+01,  2.41506896e+01,
        2.40056244e+01,  3.72997269e+01,  3.06816250e+01,  1.93607196e+01,
        2.05776606e+01,  1.70641899e+01,  1.15241219e+01,  2.40849661e+01,
        3.10697041e+01,  2.36199284e+01,  2.10421914e+01,  5.88252060e+00,
        3.03053885e+01,  3.63167383e+01,  2.16908598e+01,  3.23510449e+01,
        3.46814402e+01,  2.07641740e+01,  2.85939847e+01,  4.01152089e+01,
        3.98810686e+01,  1.27048376e+01,  2.06620305e+01,  2.52423966e+01,
        2.08504892e+00,  1.46209833e+01,  2.22242105e+01,  3.48031883e+01,
        2.60939130e+01,  2.16408781e+01,  3.03883691e+01,  2.52756205e+01,
        1.50906276e+01,  

In [29]:
y_test #real o/p of testing values

array([27.5, 21.6, 17.7, 24.3, 22.2, 50. , 18.6, 10.2, 11.3, 25.3, 14.5,
       28.6, 14.9, 34.6, 22.6, 10.9, 13.6, 22. , 20.3, 21.7, 24.3, 38.7,
       27. , 16.7, 22. , 14.9, 10.8, 22.2, 23.6, 23. , 21.5, 13.8, 50. ,
       43.8, 22.4, 28.2, 30.1, 20.4, 24.6, 50. , 46. , 16.5, 18.8, 23.3,
        8.8, 13.5, 22.5, 33.2, 23.8, 21.7, 29.4, 21.6, 16.2, 22.7, 18.5,
       18.9, 31.6, 27.5, 22.2, 12.5, 11.7, 18.8, 20.6, 20.8, 24.3, 18.6,
       15.6, 17.4, 29.8, 23.1, 30.1, 11.9, 19.8, 20. , 20.3, 17.1, 11.5,
       17.8, 13.9, 21. , 21.8, 21.2, 24.7, 12.7, 18.3, 21.1, 23. , 23.9,
       22.9, 19.5, 13.9, 30.5, 50. ,  9.5, 18.4, 17.2, 19.6, 36.1, 14.2,
       18.3, 23.5, 22.2, 13. , 13.8, 42.8, 12.1, 10.4, 20. , 50. ,  7.4,
        5. , 16.8, 13.4, 14. , 29.8, 22. , 15.7, 13.8, 20. , 13.1, 23.9,
       15.2, 29.1, 28.1, 50. , 13.6, 33.2, 21. , 42.3, 50. , 14.5,  7.2,
       31. , 27.5, 34.7, 11.7, 37. , 21. , 35.2, 20.5, 25. , 23.1, 41.3,
       19.6, 45.4, 35.4, 17.9, 48.5, 13.4, 18.9, 20

In [31]:
#To check the accuracy of theo/p obtained
from sklearn import metrics

#mean squared error- error between the real o/p and predicted o/p
metrics.mean_squared_error(y_test,y_pred)

33.86803399667014

In [33]:
#Accuracy Score
metrics.r2_score(y_test,y_pred)#best score is 1

0.6685538790447974

In [34]:
#Accuracy can be increased by changing the values pf random_state or test_size through trial and error


In [ ]:
#Gradient_Descent - optimizer
#Increases the accuracy and decreases the loss
#Epochs= passing the model multiple times, train the model multiple times 
#and we find a minima and maxima 
#Minima- the loss can be reduced to maximum 30
